name: Publish Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: |
          for rid in "win-x64" "linux-x64" "linux-arm64"; do
            dotnet publish ./PlayerLaunchScheme.csproj -c Release --sc -p:PublishReadyToRun -p:PublishSingleFile -p:PublishTrimmed -o "./publish/$rid" -r "$rid"
          done
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gitversion=$(git describe "--match=v[0-9]*.[0-9]*.[0-9]*" "--exclude=v*[!0-9]*.*[!0-9]*.*[!0-9]*" --tags)
          && gh release create "$gitversion" ./publish/*.zip --generate-notes --verify-tag
